# models/report_preview.py

from odoo import models, fields

class ReportPreview(models.TransientModel):
    _name = 'report.preview'
    _description = 'Report Preview (Temporary Records)'
    _order = 'id asc'

    # Link to the wizard
    wizard_id = fields.Many2one('reports.wizard', string='Wizard', ondelete='cascade')

    # Overview Report fields
    enquiry_number = fields.Char(string='Enquiry Number')
    enquiry_date = fields.Date(string='Enquiry Date')
    enquiry_status = fields.Char(string='Enquiry Status')
    lead_number = fields.Char(string='Lead Number')
    lead_status = fields.Char(string='Lead Status')
    lead_sales_person = fields.Char(string='Lead Sales Person')
    lead_customer_name = fields.Char(string='Lead Customer Name')
    order_type = fields.Char(string='Order Type')
    quotation_number = fields.Char(string='Quotation Number')
    sale_order_number = fields.Char(string='Sale Order Number')
    sale_order_status = fields.Char(string='Sale Order Status')
    customer_po_number = fields.Char(string='Customer PO Number')
    consignee_numbers = fields.Char(string='Consignee Numbers')
    dc_numbers = fields.Char(string='DC Numbers')
    dc_statuses = fields.Char(string='DC Status')
    dc_total = fields.Float(string='DC Total Amount')
    overview_item_names = fields.Char(string='Item Names')
    overview_item_descriptions = fields.Text(string='Item Descriptions')
    overview_item_quantities = fields.Char(string='Item Quantities')
    overview_dc_quantity = fields.Float(string='DC Quantity')
    invoice_numbers = fields.Char(string='Invoice Numbers')
    invoice_statuses = fields.Char(string='Invoice Status')
    invoice_total = fields.Float(string='Invoice Total Amount')
    installation_numbers = fields.Char(string='Installation Numbers')
    installation_statuses = fields.Char(string='Installation Status')

    # Enquiry Report fields
    customer_name = fields.Char(string='Customer Name')
    status = fields.Char(string='Status')
    contact_person = fields.Char(string='Contact Person')
    phone_number = fields.Char(string='Phone Number')
    email = fields.Char(string='Email')
    gst_number = fields.Char(string='GST Number')
    address_full = fields.Char(string='Address Full')
    sales_person = fields.Char(string='Sales Person')

    # Common Quotation fields
    quotation_number_field = fields.Char(string='Quotation Number')
    quotation_status = fields.Char(string='Status')
    quotation_customer = fields.Char(string='Customer')
    contact_person_name = fields.Char(string='Contact Person')
    contact_email = fields.Char(string='Contact Email')
    quotation_date_field = fields.Date(string='Quotation Date')
    negotiation_history = fields.Text(string='Negotiation History')
    
    # ITEM COLUMNS (repeated for each product row)
    item_name = fields.Char(string='Item Name')
    item_description = fields.Text(string='Item Description')
    item_quantity = fields.Integer(string='Item Quantity')
    item_unit_price = fields.Float(string='Item Unit Price')
    item_tax_amount = fields.Float(string='Item Tax Amount')
    item_total_amount = fields.Float(string='Item Total Amount')
    item_hsn_code = fields.Char(string='Item HSN Code')
    item_warranty = fields.Char(string='Item Warranty')
    
    # PRODUCT COLUMNS (different for each row)
    product_name = fields.Char(string='Product Name')
    product_quantity = fields.Integer(string='Product Quantity')
    product_unit_price = fields.Float(string='Product Unit Price')
    product_tax_amount = fields.Float(string='Product Tax Amount')
    product_total_amount = fields.Float(string='Product Total Amount')
    product_hsn_code = fields.Char(string='Product HSN Code')
    product_warranty = fields.Char(string='Product Warranty')
    product_margin_percentage = fields.Float(string='Product Margin %')
    product_margin_amount = fields.Float(string='Product Margin Amount')

    # Legacy fields for backward compatibility (keep existing)
    individual_price = fields.Float(string='Individual Price')
    hsn_code = fields.Char(string='HSN Code')
    quotation_quantity = fields.Integer(string='Quotation Quantity')
    tax_amount = fields.Float(string='Tax Amount')
    total_amount = fields.Float(string='Total Amount')
    warranty_details = fields.Char(string='Warranty Details')
    margin_percentage = fields.Float(string='Margin %')
    margin_amount = fields.Float(string='Margin Amount')

    # Workorder Summary Report fields
    workorder_number = fields.Char(string='WorkOrder No')
    workorder_customer = fields.Char(string='Customer')
    workorder_customer_po_number = fields.Char(string='Customer PO Number')
    workorder_po_issue_date = fields.Date(string='PO Issue Date')
    workorder_contact_person = fields.Char(string='Contact Person')
    workorder_source_quotation = fields.Char(string='Source Quotation')
    workorder_order_type = fields.Char(string='Order Type')
    workorder_gst_treatment = fields.Char(string='GST Treatment')
    workorder_created_date = fields.Date(string='Created Date')
    workorder_tax_based_on = fields.Char(string='Tax Based On')
    workorder_item_description = fields.Text(string='Item Description')
    workorder_item_name = fields.Char(string='Item Name')
    workorder_individual_price = fields.Float(string='Individual Price')
    workorder_hsn_code = fields.Char(string='HSN Code')
    workorder_quotation_quantity = fields.Integer(string='Quotation Quantity')
    workorder_tax_amount = fields.Float(string='Tax Amount')
    workorder_total_amount = fields.Float(string='Total Amount')

    # Consignee Separation Report fields
    consignee_number = fields.Char(string='Consignee No')
    consignee_location_address = fields.Char(string='Consignee Address')
    consignee_location_code = fields.Char(string='Location Code')
    consignee_customer_address = fields.Char(string='Customer with Address')
    consignee_contact_person = fields.Char(string='Contact Person')
    consignee_workorder_date = fields.Date(string='Workorder Date')
    consignee_customer_po_number = fields.Char(string='Customer PO Number')
    consignee_po_issue_date = fields.Date(string='PO Issue Date')
    consignee_item_description = fields.Text(string='Item Description')
    consignee_item_name = fields.Char(string='Item Name')
    consignee_individual_price = fields.Float(string='Individual Price')
    consignee_hsn_code = fields.Char(string='HSN Code')
    consignee_quotation_quantity = fields.Integer(string='Quotation Quantity')
    consignee_tax_amount = fields.Float(string='Tax Amount')
    consignee_total_amount = fields.Float(string='Total Amount')

    # DC Report fields
    dc_number = fields.Char(string='DC Number')
    dc_customer_po_number = fields.Char(string='Customer PO Number')
    dc_po_issue_date = fields.Date(string='PO Issue Date')
    dc_delivery_address = fields.Char(string='Delivery Address')
    dc_district = fields.Char(string='District')
    dc_state = fields.Char(string='State')
    dc_warehouse_location = fields.Char(string='Warehouse Location')
    dc_courier_direct = fields.Char(string='Courier/Direct')
    dc_item_description = fields.Text(string='Item Description')
    dc_item_name = fields.Char(string='Item Name')
    dc_individual_price = fields.Float(string='Individual Price')
    dc_hsn_code = fields.Char(string='HSN Code')
    dc_quotation_quantity = fields.Integer(string='Quotation Quantity')
    dc_tax_amount = fields.Float(string='Tax Amount')
    dc_total_amount = fields.Float(string='Total Amount')
    dc_product_name = fields.Char(string='Product Name')
    dc_serial_number = fields.Char(string='Serial Number')

    # Item Summary Report fields
    item_summary_name = fields.Char(string='Item Name')
    item_summary_code = fields.Char(string='Item Code')
    item_summary_description = fields.Text(string='Item Description')
    item_summary_category = fields.Char(string='Item Category')
    item_summary_sales_price = fields.Float(string='Sales Price')
    item_summary_cost_price = fields.Float(string='Cost Price')
    item_summary_current_stock = fields.Float(string='Current Stock')
    item_summary_unit_of_measure = fields.Char(string='Unit of Measure')
    item_summary_barcode = fields.Char(string='Barcode')
    item_summary_hsn_code = fields.Char(string='HSN Code')
    item_summary_supplier = fields.Char(string='Main Supplier')
    item_summary_location = fields.Char(string='Stock Location')

    # Task Allocation Report preview fields
    task_name = fields.Char(string='Task Name')
    task_project = fields.Char(string='Project')
    task_assigned_employee = fields.Char(string='Assigned Employee')
    task_status = fields.Char(string='Status')
    task_workorder_number = fields.Char(string='Workorder Number')
    task_customer_po_number = fields.Char(string='Customer PO Number')
    task_po_issue_date = fields.Date(string='PO Issue Date')
    task_customer = fields.Char(string='Customer')
    task_hours_logged = fields.Float(string='Hours Logged')

    # Installation Summary Report preview fields
    inst_task_name = fields.Char(string='Task Name')
    inst_project_name = fields.Char(string='Project Name')
    inst_customer = fields.Char(string='Customer')
    inst_workorder_number = fields.Char(string='Workorder Number')
    inst_customer_po_number = fields.Char(string='Customer PO Number')
    inst_po_issue_date = fields.Date(string='PO Issue Date')
    inst_assigned_employee = fields.Char(string='Assigned Employee')
    inst_deadline = fields.Date(string='Deadline')
    inst_hours_logged = fields.Float(string='Hours Logged')
    inst_dc_number = fields.Char(string='DC Number')
    inst_dc_tax_excluded = fields.Float(string='DC Tax Excluded Value')
    inst_dc_tax_included = fields.Float(string='DC Tax Included Value')
    inst_dc_status = fields.Char(string='DC Status')

    # Serial Number Product Tracking fields
    serial_lot_number = fields.Char(string='Lot/Serial Number')
    serial_workorder = fields.Char(string='Workorder')
    serial_product = fields.Char(string='Product')
    serial_created_date = fields.Date(string='Created Date')

    # Stock Summary Report fields
    stock_product_name = fields.Char(string='Product Name')
    stock_internal_ref = fields.Char(string='Internal Reference')
    stock_category = fields.Char(string='Category')
    stock_part_number_type = fields.Char(string='Part Number Type')
    stock_part_number = fields.Char(string='Part Number')
    stock_cost_price = fields.Float(string='Cost Price')
    stock_qty_on_hand = fields.Float(string='Qty On Hand')
    stock_total_price = fields.Float(string='Total Price')

    # DC Movement Report fields
    dc_movement_dc_number_val = fields.Char(string='DC Number')
    dc_movement_reference = fields.Char(string='Reference')
    dc_movement_warehouse = fields.Char(string='Warehouse')
    dc_movement_created_date = fields.Date(string='Created Date')
    dc_movement_customer = fields.Char(string='Customer')
    dc_movement_source_document = fields.Char(string='Source Document')
    dc_movement_status = fields.Char(string='Status')

    # Courier Report fields
    courier_dc_number = fields.Char(string='DC Number')
    courier_sale_number = fields.Char(string='Sale Number')
    courier_order_type_val = fields.Char(string='Order Type')
    courier_customer = fields.Char(string='Customer')
    courier_customer_po_number = fields.Char(string='Customer PO Number')
    courier_po_issue_date = fields.Date(string='PO Issue Date')
    courier_booking_date_val = fields.Date(string='Delivery Booking Date')
    courier_dc_date = fields.Date(string='DC Date')
    courier_partner_name = fields.Char(string='Courier Name')
    courier_booking_number = fields.Char(string='Courier Booking Number')
    courier_booking_date_field = fields.Date(string='Courier Booking Date')

    # Delivery Booking Summary Report fields
    db_booking_number = fields.Char(string='Delivery Booking Number')
    db_dc_number = fields.Char(string='DC Number')
    db_sale_number = fields.Char(string='Sale Number')
    db_customer_po_number = fields.Char(string='Customer PO Number')
    db_po_issue_date = fields.Date(string='PO Issue Date')
    db_dispatch_location = fields.Char(string='Dispatch Location')
    db_customer = fields.Char(string='Customer Name')
    db_billing_address = fields.Char(string='Billing Address')
    db_shipping_address = fields.Char(string='Shipping Address')
    db_contact_person = fields.Char(string='Contact Person')
    db_contact_no = fields.Char(string='Contact No')
    db_booking_date = fields.Date(string='Delivery Booking Date')
    db_dispatch_type = fields.Char(string='Dispatch Type')
    db_surface = fields.Char(string='Surface')
    db_driver_name = fields.Char(string='Driver Name')
    db_vehicle_number = fields.Char(string='Vehicle Number')
    db_status = fields.Char(string='Status')
    db_district = fields.Char(string='District')
    db_item_details = fields.Char(string='Item Name')
    db_item_description = fields.Char(string='Item Description')
    db_item_qty = fields.Char(string='Item Qty')
    db_unit_price = fields.Float(string='Unit Price')
    db_dc_value = fields.Float(string='DC Value')
    db_invoice_no = fields.Char(string='Invoice No')

    # Purchase Order Report fields
    po_number = fields.Char(string='PO Number')
    po_vendor = fields.Char(string='Vendor')
    po_salesperson = fields.Char(string='Salesperson')
    po_created_date = fields.Date(string='Created Date')
    po_expected_arrival = fields.Date(string='Expected Arrival')
    po_status = fields.Char(string='Status')
    po_purchase_indent = fields.Char(string='Purchase Indent')
    po_work_order_no = fields.Char(string='Work Order No')
    po_customer_po_number = fields.Char(string='Customer PO Number')
    po_po_issue_date = fields.Date(string='PO Issue Date')
    po_grn_numbers = fields.Char(string='GRN Inward Numbers')
    po_grn_date = fields.Char(string='GRN Done Date')
    po_grn_status = fields.Char(string='GRN Inward Status')
    po_purchase_person = fields.Char(string='Purchase Person')
    po_product = fields.Char(string='Product')
    po_description = fields.Text(string='Description')
    po_qty_ordered = fields.Float(string='Qty Ordered')
    po_qty_received = fields.Float(string='Qty Received')
    po_qty_billed = fields.Float(string='Qty Billed')
    po_uom = fields.Char(string='UOM')
    po_unit_price = fields.Float(string='Unit Price')
    po_subtotal = fields.Float(string='Subtotal')
    po_total = fields.Float(string='Total')

    # Purchase Indent Report fields
    pi_indent_no = fields.Char(string='Indent No')
    pi_indent_date = fields.Date(string='Indent Date')
    pi_order_type = fields.Char(string='Order Type')
    pi_sale_order = fields.Char(string='Sale Order')
    pi_approved_date = fields.Date(string='Indent Approved Date')
    pi_vendor = fields.Char(string='Vendor')
    pi_status = fields.Char(string='Status')
    pi_product = fields.Char(string='Product')
    pi_part_number = fields.Char(string='Part Number')
    pi_qty = fields.Float(string='Qty')
    pi_price = fields.Float(string='Price')
    pi_uom = fields.Char(string='UOM')

    # Invoice Summary Report fields
    inv_number = fields.Char(string='Invoice Number')
    inv_customer = fields.Char(string='Customer')
    inv_date = fields.Date(string='Invoice Date')
    inv_due_date = fields.Date(string='Due Date')
    inv_dc_number = fields.Char(string='DC Number')
    inv_work_order = fields.Char(string='Work Order')
    inv_po_number = fields.Char(string='PO Number')
    inv_po_issue_date = fields.Date(string='PO Issue Date')
    inv_invoice_type = fields.Char(string='Invoice Type')
    inv_status = fields.Char(string='Status')
    inv_item = fields.Char(string='Item')
    inv_item_name = fields.Char(string='Item Name')
    inv_description = fields.Text(string='Description')
    inv_qty = fields.Integer(string='Quantity')
    inv_taxes = fields.Char(string='Taxes')
    inv_subtotal = fields.Float(string='Subtotal')

    # Product Summary Report fields
    ps_name = fields.Char(string='Product Name')
    ps_internal_ref = fields.Char(string='Internal Reference')
    ps_category = fields.Char(string='Category')
    ps_product_type = fields.Char(string='Product Type')
    ps_uom = fields.Char(string='UOM')
    ps_sales_price = fields.Float(string='Sales Price')
    ps_cost_price = fields.Float(string='Cost Price')
    ps_hsn_code = fields.Char(string='HSN Code')
    ps_barcode = fields.Char(string='Barcode')
    ps_qty_on_hand = fields.Float(string='Qty On Hand')
    ps_vendor = fields.Char(string='Main Vendor')
    ps_part_number_type = fields.Char(string='Part Number Type')
    ps_part_number = fields.Char(string='Part Number')
                            
    # Delivered/Undelivered Summary Report fields
    du_workorder_no = fields.Char(string='Workorder No')
    du_customer = fields.Char(string='Customer')
    du_customer_po_number = fields.Char(string='Customer PO Number')
    du_po_issue_date = fields.Date(string='PO Issue Date')
    du_order_type = fields.Char(string='Order Type')
    du_salesperson = fields.Char(string='Salesperson')
    du_submitted_to_customer = fields.Char(string='Invoice Submitted to Customer')
    du_submitted_date = fields.Date(string='Submitted Date')
    du_item_name = fields.Char(string='Item Name')
    du_item_description = fields.Text(string='Item Description')
    du_workorder_qty = fields.Float(string='Workorder Qty')
    du_unit_price = fields.Float(string='Unit Price')
    du_total_amount = fields.Float(string='Total Amount')
    du_delivered_qty = fields.Float(string='Delivered Qty')
    du_delivered_amount = fields.Float(string='Delivered Amount')
    du_undelivered_qty = fields.Float(string='Undelivered Qty')
    du_undelivered_amount = fields.Float(string='Undelivered Amount')
    du_inst_completed_qty = fields.Float(string='Installation Completed Qty')
    du_inst_completed_value = fields.Float(string='Installation Completed Value')
    du_inst_incomplete_qty = fields.Float(string='Installation Incomplete Qty')
    du_inst_incomplete_value = fields.Float(string='Installation Incomplete Value')


    